#!/usr/bin/env python3

import json
import os
import sys
import http.server
import socketserver


class Handler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Hyperlinks with anchors seem to work fine in Microsoft Excel.
        # However, they are broken in Apple Numbers. Here is a workaround.
        i = self.path.find('%23')
        if i == -1:
            http.server.SimpleHTTPRequestHandler.do_GET(self)
        else:
            p = self.path.replace('%23', '#')
            self.send_response(301)
            self.send_header('Location', self.server.base_url + p)
            self.end_headers()


class Server(socketserver.TCPServer):
    allow_reuse_address = True


def main():
    param = sys.argv[1:]
    if len(param) != 1:
        sys.exit('usage: {} CONFIGURATION'.format(sys.argv[0]))
    with open(param[0]) as f:
        cfg = json.load(f)
    d = cfg.get('output-dir', 'output')
    p = cfg.get('server-port', 8000)
    os.chdir(d)
    httpd = Server(("localhost", p), Handler)
    httpd.allow_reuse_address = True
    httpd.base_url = 'http://localhost:{}'.format(p)
    print('Server started, hit ctrl-c to stop.')
    print('{} now refers to {}'.format(httpd.base_url, os.getcwd()))
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print('\nStop.')

main()

